apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: manara-ingress
  namespace: manara
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "Referrer-Policy: strict-origin-when-cross-origin";
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.manaraos.ae
        - api.manaraos.ae
        - "*.manaraos.ae"
      secretName: manara-tls
  rules:
    - host: api.manaraos.ae
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: manara-api
                port:
                  number: 3001
    - host: app.manaraos.ae
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: manara-web
                port:
                  number: 3000
    - host: "*.manaraos.ae"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: manara-web
                port:
                  number: 3000
