apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namePrefix: ""

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: manara-api
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: manara-web
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: manara-worker

images:
  - name: registry.manaraos.ae/manara-api
    newTag: "$(IMAGE_TAG)"
  - name: registry.manaraos.ae/manara-web
    newTag: "$(IMAGE_TAG)"

configMapGenerator:
  - name: manara-api-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=warn
